require_relative './lib/Pawn.rb'
require_relative './lib/rook.rb'
require_relative './lib/bishop.rb'
require_relative './lib/knight.rb'
require_relative './lib/king.rb'
require_relative './lib/queen.rb'
require_relative './lib/piece.rb'
require_relative './lib/board.rb'